### ISSUE TITLE
findValueForJsonPath always returns 'path can not be null or empty'

### ISSUE THREAD

**Issue by studiovlijmscherp** [societe-generale/github-crawler#115]
## Summary
We're crawling all our repo's to find version numbers of certain packages. 
Console logs 'processing repo ... xyz' for all repos so we are connected to Github.

When using findPropertyValueInYamlFile (for another property). Parsing works as expected:

```
    indicatorsToFetchByFile:
      "[composer.lock]":
          - name: content_hash
            type: findPropertyValueInYamlFile
            params:
              propertyName: "content-hash"
```

When using findValueForJsonPath, an error is returned:

```
indicatorsToFetchByFile:
      "[composer.lock]":
          - name: content_hash_path
            type: findValueForJsonPath
            params:
              propertyName: "$.content-hash"
```

error:
```
2023-01-10 14:05:06.368 ERROR 92041 --- [           main] ication$$EnhancerBySpringCGLIB$$ffb279df : problem while running github crawler
java.lang.IllegalArgumentException: path can not be null or empty
```

## Type of Issue

It is a : 
 - [x ] bug
 - [ ] request
 - [ x] question regarding the documentation

## Your Environment

* Version used: github-crawler-starter-2.1.0-exec.jar
* OS and version: MacOs 13.0.1 (22A400)

**Comment by vincent-fuchs** [comment]
Hi, thanks for reporting the issue. Is there any chance to get a more complete stacktrace ? I can't do much with what you've provided, it doesn't even show from where the exception is thrown.

**Comment by vincent-fuchs** [comment]
one strong possibility though : 

for the findPropertyValueInYamlFile parser, the expected parameter is indeed `propertyName `: https://github.com/societe-generale/github-crawler/blob/master/github-crawler-core/src/main/kotlin/com/societegenerale/githubcrawler/parsers/YamlParserForPropertyValue.kt#L12

However, for findValueForJsonPath parser, the expected parameter is `jsonPath `: https://github.com/societe-generale/github-crawler/blob/master/github-crawler-core/src/main/kotlin/com/societegenerale/githubcrawler/parsers/JsonPathParser.kt#L18

please give it a try and let me know if that helps

**Comment by studiovlijmscherp** [comment]
Thanks!

Changing propertyName to jsonPath did get met one step further. I'm able to find some basic values.
Searching for a key/value still returns an error.

Trying to search for these vales:
```
    indicatorsToFetchByFile:
      "[composer.lock]":
          - name: package_version
            type: findValueForJsonPath
            params:
              jsonPath: "$.packages[?(@.name == 'sulu/sulu')].name"
```

**Returns the following error:**

```
2023-01-16 15:02:30.110 ERROR 31371 --- [main] lication$$EnhancerBySpringCGLIB$$d72a6fb : problem while running github crawler
java.lang.ClassCastException: net.minidev.json.JSONArray cannot be cast to java.lang.String at com.societegenerale.githubcrawler.parsers.JsonPathParser.internalParseFileContentForIndicator(JsonPathParser.kt:37) ~[github-crawler-core-2.1.0.jar!/:2.1.0]
```

Attached is an example of the file I'm crawling
[composer.lock.zip](https://github.com/societe-generale/github-crawler/files/10426515/composer.lock.zip)

When evaluating the jsonPath @ https://jsonpath.com/ - the correct values are being returned.
